# General Configurations for the VRP Simulation
NUM_NODES = 10
NUM_TRUCKS = 5  # Ignore this for now
TRUCK_CAPACITY = int((NUM_NODES + NUM_TRUCKS - 1) // NUM_TRUCKS * 1.25)

# Disruptions
DISRUPTION_PROB = 0.02
RECOVERY_PROB = 0.15

# Eligibility Traces
LAMBDA = 0.95

# Epsilon-greedy Config:
EPSILON_START = 0.95
EPSILON_MIN = 0.05
EPSILON_DECAY = 0.995
EPSILON_DECAY_RECOVERING = 0.9998
EPSILON_DECAY_REBALANCING = 0.9998
LEARNING_RATE = 0.05
DISCOUNT_FACTOR = 0.95
DECAY_EVERY = 50

# Visualization Config:
WINDOW_W = 1920
WINDOW_H = 1080
GRAPH_W = 1360
HUD_W = WINDOW_W - GRAPH_W
FPS_CAP = 1000
SIM_STEP_MS = 500
FONT_SIZE = 25
FONT_SIZE_SMALL = int(FONT_SIZE * 0.75)
FONT_SIZE_LARGE = int(FONT_SIZE * 1.25)
PLOT_EVERY = 1000

# Main runtime configuration
AGENT_MODE = "transformer"  # "transformer" or "fuzzy"
CHECKPOINT_TRANSFORMER_PATH = "checkpoints/transformer.pt"
CHECKPOINT_FUZZY_PATH = "checkpoints/fuzzy.pkl"
POLL_INTERVAL_S = 2.0
DEFAULT_SPEED = 0.04
SPEED_STEP = 0.01
SPEED_MIN = 0.005
SPEED_MAX = 1.0

# Speed slider geometry
SLIDER_X = 20
SLIDER_Y_OFFSET = 40
SLIDER_W = 300
SLIDER_MAX_SPEED = 0.15
